server:
  port: 8055

spring:
  profiles:
    active: dev
  h2:
    console:
      enabled: true
    settings:
    #        web-allow-others: false
    # 默认路径，则网页访问H2路径http://localhost:8068/h2-console
    path: /h2-console

  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/your_database
    username: your_username
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA configuration
  jpa:
    # sqlite need
    #    database-platform: org.hibernate.community.dialect.SQLiteDialect
    properties:
      hibernate:
        hbm2ddl:
          auto: create

        #        dialect: org.hibernate.dialect.MYSQL5InnoDBDialect
        # format SQL output
        format_sql: true
    # SQL output
    show-sql: true


#javafx:
#  appicons: app-icon.png
#  stage:
#    resizable: false
#  title: Lab Central

insertExample: "示例：H1299 + (0,a20,ZA1a20,ZA5a20,ZA10a20,ZA10) -1h+10min"