spring:
  jmx:
    enabled: false
javafx:
  stage:
    resizable: false
  title: Lab Central

fonts: Roboto-Black.ttf, Roboto-BlackItalic.ttf

insertExample: " \n
  示例：\n
  [20230909]\n
  H1299 + (0,a20,ZA1a20,ZA5a20,ZA10a20,ZA10) -1h+10min \n
  H1299 + (0,b10,ZA1b10,ZA5b10,ZA10b10,ZA10) -1h+10min"


#fonts:
#  - Roboto-Black.ttf
#  - Roboto-BlackItalic.ttf

#fonts:
#  list:
#    - Roboto-Black.ttf
#    - Roboto-BlackItalic.ttf
#  - Roboto-Bold.ttf
#  - Roboto-BoldItalic.ttf
#  - Roboto-Italic.ttf
#  - Roboto-Light.ttf
#  - Roboto-LightItalic.ttf
#  - Roboto-Medium.ttf
#  - Roboto-MediumItalic.ttf
#  - Roboto-Regular.ttf
#  - Roboto-Thin.ttf
#  - Roboto-ThinItalic.ttf